; Mapper support
external	mapper_init	; Initialize the mapper routines
external	mapper_get_pslot	; Get primary mapper slot address
external	mapper_get_table	; Get address of mapper variables table

; Copy of the MSX-DOS2 mapper support routines
external	ALL_SEG
external	FRE_SEG
external	RD_SEG
external	WR_SEG
external	CAL_SEG
external	CALLS
external	PUT_PH
external	GET_PH
external	PUT_P0
external	GET_P0
external	PUT_P1
external	GET_P1
external	PUT_P2
external	GET_P2
external	PUT_P3
external	GET_P3
